# Copyright 2024 - Andrew Kwok Fai LUI, Robotics and Autonomous System Group,
# Research Engineering Facility, RI
# the Queensland University of Technology

ARG ROS_DISTRO=noetic

FROM osrf/ros:${ROS_DISTRO}-desktop-full
LABEL author="Andrew Lui <luia2@qut.edu.au>"

ARG USER=qcr
ENV USER=${USER}
ENV ROS_DISTRO=${ROS_DISTRO}

# update apt-get and add user 'qcr' grant sudo privilege
RUN apt-get update && \
    apt-get install -y sudo && \
    adduser --disabled-password --gecos "" qcr  && \
    echo "${USER} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER ${USER}
WORKDIR /home/${USER}
SHELL ["/bin/bash", "-c"]
ENV CGRAS_WS=/home/${USER}/cgras_ws
# install cgras workspace
RUN mkdir -p ${CGRAS_WS}/src
# RUN cd ${CGRAS_WS}/src && \ 
# git clone git@github.com:Coral-Imaging/cgras_imaging_agent.git

# install base packages
RUN sudo DEBIAN_FRONTEND=noninteractive apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
lsb-release \
git \
openssh-server \
ca-certificates \
net-tools \
locales \
figlet \
curl \
iputils-ping \
vim

RUN git config --global core.editor "vim"

RUN sudo DEBIAN_FRONTEND=noninteractive apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
wget \
software-properties-common \
dbus \
htop \
build-essential \
cmake \
gdb

# install python
RUN sudo add-apt-repository ppa:deadsnakes/ppa

# RUN sudo DEBIAN_FRONTEND=noninteractive apt-get update && sudo apt-get upgrade -y python3.9 

# install python
RUN sudo DEBIAN_FRONTEND=noninteractive apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
python3-pip \
python3-rospkg \
python3-rosdep \
python3-setuptools \
python3-tk

# install ur message for coordinator (NOTE: a better design is to encapsulate ur dependencies within the robot ros node) 
RUN sudo DEBIAN_FRONTEND=noninteractive apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
ros-noetic-ur-dashboard-msgs

# workspace create and make 
RUN source /opt/ros/${ROS_DISTRO}/setup.bash && \
cd ${CGRAS_WS} && \
catkin_make -DPYTHON_EXECUTABLE=/usr/bin/python3

# install python modules
COPY assets/requirements.txt ${CGRAS_WS}/src/requirements.txt
RUN pip install -r ${CGRAS_WS}/src/requirements.txt
RUN rm ${CGRAS_WS}/src/requirements.txt

# install yolo and pytorch
# RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu101
RUN pip install networkx==3.1 ultralytics>=8.3
# ultralytics pulls in opencv-python which overwrites opencv-contrib-python's cv2 binding;
# reinstall contrib to restore cv2.detail stitching API compatibility
RUN pip uninstall -y opencv-python && pip install opencv-contrib-python==4.8.1.78

# complete rosdep installation
RUN rosdep update

# set locales
RUN sudo locale-gen en_US.UTF-8  
RUN sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8  
ENV LANGUAGE=en_US:en  
ENV LC_ALL=en_US.UTF-8

RUN echo "source banner" >> ~/.bashrc
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> ~/.bashrc
RUN echo "source ${CGRAS_WS}/devel/setup.bash" >> ~/.bashrc 
# install the qcr banner
COPY assets/banner.sh /usr/local/bin/banner
# copy and define entry script
COPY ./entrypoint_setup.sh /usr/local/bin/ros_entrypoint
RUN sudo chmod +x /usr/local/bin/ros_entrypoint
ENTRYPOINT ["/usr/local/bin/ros_entrypoint"]
CMD ["bash"]
