# YAML file for the system
---
cgras_detector:
  # WEB INTERFACE
  # main web server
  web_host: 0.0.0.0
  web_port: 8023
  web_debug_mode: False          # for developers' use and not to be adjusted
  web_debug_hot_reload: False   # for developers' use and not to be adjusted

  # auxillary web server
  aux_web_host: 0.0.0.0
  aux_web_port: 8024
  aux_web_directory: ~/cgras_data/detector/data   # for developers' use and not to be adjusted

  # timers for driving the system and refresh the GUI
  system_timer: 0.5  # seconds
  dashboard_refresh_cycles: 2  # refresh rate of dashboard, the unit is system timer cycles

  # CGRAS INTEGRATION
  # default ros topics for the states of the coordinator and detector
  ros_coordinator_state_topic: '/cgras/coordinator/state' 
  ros_detector_state_topic: '/cgras/detector/state' 

  # default ros topic for the service for querying tile sample
  ros_query_tile_samples_topic: '/cgras/coordinator/query_tile_samples'

  # suspend operation when executing a capture image program
  suspend_when_capturing_image: False

  # connection timeout
  connection_timeout: 120   # seconds

  # OPERATION
  # the data folder
  cgras_data_folder: ~/cgras_data
  disk_space_min: 2.0                   # GBytes
  # the import image folder
  # cgras_captured_images_folder: /home/qcr/cgras_data/images/{tile_id}_{batch_id}/Export

  # automation mode (whether the task execution is automated)
  task_automation: True 

  # yolo model range
  max_coral_age: 120  # days

  # heatmap properties
  heatmap_colour_scale: viridis
  heatmap_show_label_slider_max: 30

  # MODELS AND ALGORITHMS
  # detection task parameters: reconstruction
  task_params_filename: params.yaml             # for developers' use and not to be adjusted
  reco_model_filename: reco_model.yaml          # for developers' use and not to be adjusted
  loctile_model_filename: loctile_model.yaml    # for developers' use and not to be adjusted
  cod_model_filename: coral_object_detect_model.yaml  # for developers' use and not to be adjusted
  output_jpeg_quality: 70                      # JPEG quality for all output images (1-100); lower values reduce disk usage
  reco_working_scale: 0.08                     # the scale at which the reconstruction process operate on the images, default 0.10
  reco_tab_grid_image: True                    # output tab grid annotated images after tile location (working scale always)
  reco_manual_validation_original_scale: True  # output annotated and tab-grid images at original scale for manual validation
  reco_debug_images_at_original_scale: False   # output all intermediate reconstruction images at original scale (large disk usage)
  reco_debug_feature_matching_images: True
  reco_feature_detectors: ['akaze', 'brisk', 'sift']     # sift, orb, brisk, akaze 
  reco_feature_matching_confidence_threshold: 0.8    # default 1.2
  reco_image_matching_min_confidence: 0.8   # between rows matching confidence, default 1.2
  reco_image2d_matching_min_confidence: 0.8 # row matching confidence, default 1.2
  # reco_error_correction: False            # for developers' use and not to be adjusted
  reco_aspect_ratio_roi_error_rel: 0.1           # the maximum relative error of aspect ratio of rois from that of the original image (default: 0.1)
  reco_misplaced_roi_erro_rel: 0.1               # the maximum relative error of roi corner placement with respect to the roi sizes (default 0.1)

  # NOTE: model of the tile holder and frame (OBSOLETE), must be provided by tile sample
  # tile_size_in_mm: [294, 294]  # default value, only if not defined in the metadata of the tile_sample 
  # frame_size_in_mm: [280, 280] # default value, only if not defined in the metadata of the tile_sample 

  # detection task parameters: locate tile
  # NOTE for 2024 cgars dataset/aims camera trolley images:
  # loctile_template_size was 60
  # loctile_template_corner_size was 12
  loctile_pixel_classifier_filename: train_set_BLUE_20260514_hsv.model
  loctile_rotate_angle_max: 3.0   # degrees
  loctile_aspect_ratio_diff_max_rel: 0.05   # 0.05 relative difference
  loctile_aspect_ratio_diff_max_abs: 0.05   # 0.05 absolute difference
  loctile_debug_images: True
  loctile_template_size: 60
  loctile_template_corner_size: 12
  loctile_working_scale: 0.1
  loctile_template_type: block
  # detection task parameters: object detection  



# the parameters for the object detection model and post-processing
  cod_debug_blob_images: False
  cod_blob_overlap_pix: 128
  cod_use_cached_object_detection: True
  cod_coral_child_min_overlap_ratio: 0.25         # the pverlap ratio of a polyp_single or polyp_keypart that is considered a child of a polyp_multi
  cod_merge_mutli_models: True                # merge the detection result with duplication removal
  
  # detection task parameters: object detection classification
  cod_mask_polyp_keypart: False
